apiVersion: v1
kind: Service
metadata:
  name: wallet-msgtransfer-service
spec:
  selector:
    app: wallet-msgtransfer-server
  ports:
    - name: prometheus
      protocol: TCP
      port: 19020
      targetPort: 19020
  type: ClusterIP
