apiVersion: v1
kind: Secret
metadata:
  name: openim-mysql-secret
type: Opaque
data:
  mysql_openim_uri: "aW1XYWxsZXQ6MW1XNGxsZTN0U3RhZzIwMjVAdGNwKG15c3FsLXByaW1hcnkuYWthLXN0YWdpbmcuc3ZjLmNsdXN0ZXIubG9jYWw6MzMwNikvYWthX3dhbGxldHM/Y2hhcnNldD11dGY4bWI0JnBhcnNlVGltZT1UcnVlJmxvYz1Mb2NhbA=="
  mysql_openim_username: "aW1XYWxsZXQ="
  mysql_openim_password: "MW1XNGxsZTN0U3RhZzIwMjU="
