apiVersion: v1
kind: Service
metadata:
  name: im-wallet-api-service
spec:
  selector:
    app: im-wallet-api
  ports:
    - name: http
      protocol: TCP
      port: 10011
      targetPort: 10011
    - name: prometheus
      protocol: TCP
      port: 13002
      targetPort: 13002
  type: NodePort
