apiVersion: v1
kind: ConfigMap
metadata:
  name: im-wallet-config
data:
  discovery.yml: |
    enable: "kubernetes"
    etcd:
      rootDirectory: openim
      address: [ localhost:12379 ]
      username: ''
      password: ''
    
    kubernetes:
      namespace: aka-staging
    
    rpcService:
      wallet: wallet-rpc-service
      admin: admin-rpc-service
  
  share.yml: |
    openIM:
      # OpenIM API address
      apiURL: http://18.142.142.4:10002
      # OpenIM secret key, must be consistent with OpenIM
      secret: openIM123
      # OpenIM administrator userID, must be consistent with OpenIM
      adminUserID: imAdmin
    walletAdmin:
      # Default username and password for the admin
      - "walletAdmin"
    dbOption: mysql

  log.yml: |
    # Log storage path, default is acceptable, change to a full path if modification is needed
    storageLocation: ./logs/
    # Log rotation period (in hours), default is acceptable
    rotationTime: 24
    # Number of log files to retain, default is acceptable
    remainRotationCount: 2
    # Log level settings: 3 for production environment; 6 for more verbose logging in debugging environments
    remainLogLevel: 6
    # Whether to output to standard output, default is acceptable
    isStdout: true
    # Whether to log in JSON format, default is acceptable
    isJson: false
    # output simplify log when KeyAndValues's value len is bigger than 50 in rpc method log
    isSimplify: true

  admin.yml: |
    tokenPolicy:
      expire: 90

    secret: chat123
  
  kafka.yml: |
    username: ''
    password: ''
    producerAck: 
    compressType: none
    address: [ boot-1z2.akachatmsk.4bqo48.c3.kafka.ap-southeast-1.amazonaws.com:9096,boot-nqv.akachatmsk.4bqo48.c3.kafka.ap-southeast-1.amazonaws.com:9096,boot-9o4.akachatmsk.4bqo48.c3.kafka.ap-southeast-1.amazonaws.com:9096 ]
    toExpiredTransferTopic: toExpiredTransfer
    toExpiredEnvelopeTopic: toExpiredEnvelope
    toExpiredTransferGroupID: toExpiredTransferGroupID
    toExpiredEnvelopeGroupID: toExpiredEnvelopeGroupID
    tls:
      enableTLS: true
      caCrt: /certs/amazon-ca.pem
      clientCrt: 
      clientKey: 
      clientKeyPwd: 
      insecureSkipVerify: false
  
  mysqldb.yml: |
    # URI for database connection, leave empty if using address and credential settings directly
    uri: "imWallet:1mW4lle3tStag2025@tcp(mysql-primary.aka-staging.svc.cluster.local:3306)/aka_wallets?charset=utf8mb4&parseTime=True&loc=Local"
    # Hostname or IP address of PostgreSQL server
    host: mysql-primary.aka-staging.svc.cluster.local
    # Port of PostgreSQL server
    port: 3306
    # Name of the database
    database: aka_wallets
    # Username for database authentication
    username: imWallet
    # Password for database authentication
    password: 1mW4lle3tStag2025
    # SSL mode (disable, require, verify-ca, verify-full)
    sslmode: disable
    # Maximum number of open connections in the pool
    maxOpenConns: 300
    # Maximum number of idle connections in the pool
    maxIdleConns: 30
    # Maximum number of retry attempts for a failed database connection
    maxRetry: 10
    # Connection timeout in seconds
    connectTimeout: 5

  postgresdb.yml: |
    # URI for database connection, leave empty if using address and credential settings directly
    uri: ""
    # Hostname or IP address of PostgreSQL server
    host: localhost
    # Port of PostgreSQL server
    port: 5432
    # Name of the database
    database: openim_v3
    # Username for database authentication
    username: root
    # Password for database authentication
    password: openIM123
    # SSL mode (disable, require, verify-ca, verify-full)
    sslmode: disable
    # Maximum number of open connections in the pool
    maxOpenConns: 100
    # Maximum number of idle connections in the pool
    maxIdleConns: 10
    # Maximum number of retry attempts for a failed database connection
    maxRetry: 10
    # Connection timeout in seconds
    connectTimeout: 5

  redis.yml: |
    address: [ akachat-cache-valkey-serverless-el5e9i.serverless.apse1.cache.amazonaws.com:6379 ]
    username: 
    password:
    clusterMode: true
    db: 0
    maxRetry: 10
    poolSize: 300
    tls:
      enableTLS: true
      serverName: "akachat-cache-valkey-serverless-el5e9i.serverless.apse1.cache.amazonaws.com"

  msgtransfer.yml: |
    prometheus:
      enable: true
      autoSetPorts: true
      ports: [ 19020 ]

  publisher.yml: |
    prometheus:
      enable: true
      autoSetPorts: true
      ports: [ 19023 ]
  
  wallet-api-wallet.yml: |
    api:
      # Listening IP; 0.0.0.0 means both internal and external IPs are listened to, default is recommended
      listenIP: 0.0.0.0
      # Listening ports; if multiple are configured, multiple instances will be launched
      ports: [ 10011 ]
      # API compression level; 0: default compression, 1: best compression, 2: best speed, -1: no compression
      compressionLevel: 0

    prometheus:
      enable: false
      autoSetPorts: true
      ports: [ 13002 ]
      grafanaURL: http://127.0.0.1:13000/

