username: ''
password: ''
producerAck: 
compressType: none
address: [ localhost:19094 ]
toExpiredTransferTopic: toExpiredTransfer
toExpiredEnvelopeTopic: toExpiredEnvelope
toExpiredTransferGroupID: toExpiredTransferGroupID
toExpiredEnvelopeGroupID: toExpiredEnvelopeGroupID
tls:
  enableTLS: false
  caCrt: 
  clientCrt: 
  clientKey: 
  clientKeyPwd: 
  insecureSkipVerify: false
