openIM:
  # OpenIM API address
  apiURL: http://127.0.0.1:10004
  # OpenIM secret key, must be consistent with OpenIM
  secret: openIM123
  # OpenIM administrator userID, must be consistent with OpenIM
  adminUserID: imAdmin

walletAdmin:
   # Default username and password for the admin
  - "walletAdmin"

dbOption: mysql
